package es.uvigo.ei.sing.hlfernandez.hellospeedment;

import com.speedment.internal.core.runtime.SpeedmentApplicationLifecycle;
import es.uvigo.ei.sing.hlfernandez.hellospeedment.db0.hellospeedment.user.impl.UserManagerImpl;
import javax.annotation.Generated;

/**
 * A {@link
 * com.speedment.internal.core.runtime.SpeedmentApplicationLifecycle} class
 * for the {@link com.speedment.config.Project} named hellospeedment.
 * <p>
 * This Class or Interface has been automatically generated by Speedment. Any
 * changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment
 */
@Generated("Speedment")
public class HellospeedmentApplication extends SpeedmentApplicationLifecycle<HellospeedmentApplication> {
    
    public HellospeedmentApplication() {
        setSpeedmentApplicationMetadata(new HellospeedmentApplicationMetadata());
    }
    
    @Override
    protected void onInit() {
        super.onInit();
        loadAndSetProject();
        put(new UserManagerImpl(speedment));
    }
}